# Generated by Django 5.0.1 on 2024-02-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-id'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
